DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
enum	INTEGER			NOT NULL,
skill	VARCHAR(30)		NOT NULL,
hobby	VARCHAR(30)		NOT NULL,
	CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY(enum, skill, hobby) );
	
INSERT INTO EMPLOYEE VALUES(007, 'programming', 'swimming');
INSERT INTO EMPLOYEE VALUES(007, 'cooking', 'swimming');
INSERT INTO EMPLOYEE VALUES(007, 'programming', 'hiking');
INSERT INTO EMPLOYEE VALUES(007, 'cooking', 'hiking');

COMMIT;

SELECT * FROM EMPLOYEE;

DROP TABLE EMPLOYEE;

