DROP TABLE ROOM;

CREATE TABLE ROOM(
bldgnum		INTEGER 	NOT NULL,
bldgname	VARCHAR(30)	NOT NULL, 
roomnum		INTEGER		NOT NULL,
area		INTEGER		NOT NULL,
	CONSTRAINT ROOM_PKEY PRIMARY KEY(bldgnum, roomnum) );
	
INSERT INTO ROOM VALUES ( 3, 'SCIT', 210, 20);
INSERT INTO ROOM VALUES ( 3, 'SCIT', 211, 22);
INSERT INTO ROOM VALUES ( 3, 'SCIT', 213, 20);

COMMIT;

SELECT * FROM ROOM;

