DROP TABLE SUPPLIER;
DROP TABLE COMPANY;

CREATE TABLE SUPPLIER(
sname	VARCHAR(20)	NOT NULL,
city	VARCHAR(20)	NOT NULL,
	CONSTRAINT SUPPLIER_PKEY PRIMARY KEY(sname, city) );

CREATE TABLE COMPANY(
cname	VARCHAR(20)	NOT NULL,
city	VARCHAR(20)	NOT NULL,
		CONSTRAINT COMPANY_PKEY PRIMARY KEY(cname, city) );
		
INSERT INTO SUPPLIER VALUES( 'James', 'Paris');
INSERT INTO SUPPLIER VALUES( 'Robin', 'Rome');
INSERT INTO SUPPLIER VALUES( 'Harry', 'Paris');

INSERT INTO COMPANY VALUES( 'Golden Bolts',  'Paris');
INSERT INTO COMPANY VALUES( 'Golden Bolts',  'Rome');
INSERT INTO COMPANY VALUES( 'Lazy Lobster', 'Rome');

COMMIT;

SELECT * FROM SUPPLIER;
SELECT * FROM COMPANY;
SELECT * FROM SUPPLIER JOIN COMPANY ON SUPPLIER.CITY = COMPANY.CITY;

DROP TABLE SUPPLIER;
DROP TABLE COMPANY;